Developer readme
ghga-de/file-services-backend pull request #4
Opened 2024-05-22 13:34 UTC by TheByronHimes

2024-05-23 07:27 UTC, mephenor requested changes
Good job on the general dev_guide.
There are some smaller phrasing issues and some points that need a bit more discussion, though.

2024-05-23 07:56 UTC, TheByronHimes commented on .readme_generation/dev_guide.md
> +  that are controlled by the Microservice Template Repository and used for development
I think we definitely need a version of that script to keep at least that file in check, but there are probably other things that need to/can be synced too.

2024-05-23 07:59 UTC, TheByronHimes commented on .readme_generation/dev_guide.md
> +2. `.pyproject_generation/pyproject_custom.toml` is used to define production-specific
@mephenor Are the application dependencies for all services not aggregated in the pyproject.toml?

2024-05-23 08:13 UTC, TheByronHimes commented on .readme_generation/dev_guide.md
> +which is then pushed to Docker Hub.
Okay. I'll replace this with TBD and circle back once we've got a concrete solution.

2024-05-23 08:23 UTC, TheByronHimes commented on .readme_generation/dev_guide.md
> +| [`/example_data`](/example_data) | Can be used to populate the application with data for test/dev |
Removed

2024-05-23 08:23 UTC, TheByronHimes commented on .readme_generation/dev_guide.md
> +run to update the `pyproject.toml` file at the root level.
Reworded

2024-05-23 08:24 UTC, TheByronHimes commented on .readme_generation/dev_guide.md
> +Configuration is stored in `.yaml` format at the service level. I.e., there is one config
Thanks

2024-05-23 08:24 UTC, TheByronHimes commented on .readme_generation/dev_guide.md
> +`services/<service_name>/tests_<service_name>`.
Added

2024-05-23 08:24 UTC, TheByronHimes commented on .readme_generation/dev_guide.md
> +- `scripts/`: Required only if the service uses FastAPI for a REST API.
Thanks

2024-05-23 11:45 UTC, mephenor commented on .readme_generation/dev_guide.md
> +2. `.pyproject_generation/pyproject_custom.toml` is used to define production-specific
Yep, but the production specific wording is misleading as those are also needed for testing, etc.

2024-05-23 11:46 UTC, mephenor commented on .readme_generation/dev_guide.md
> +  that are controlled by the Microservice Template Repository and used for development
I'll add that to my TODO list for the end of the day

2024-05-23 13:07 UTC, TheByronHimes commented on .readme_generation/dev_guide.md
> +2. `.pyproject_generation/pyproject_custom.toml` is used to define production-specific
I changed it to eliminate ambiguity. Take a look at [13ac5db](https://github.com/ghga-de/file-services-backend/pull/4/commits/13ac5db7b9891361556f42694528409c078fbb80)

2024-05-24 10:53 UTC, mephenor approved these changes

2024-05-24 10:57 UTC, merged